---
- name: Gather system facts
  hosts: all
  tasks:
    - name: Gather facts
      setup:
      register: system_facts
    - name: Print
      debug:
        msg: "{{ system_facts.stdout_lines }}"

