---
- name: check  
  hosts: test
  become: true
  tasks:
    - name: check  
      shell: free -h | grep Mem
      register: command_output
    - name: Print
      debug:
        msg: "{{ command_output.stdout_lines }}"
